teste: ordenacao.o 
	gcc -Wall -pedantic -ansi -g teste.o -o teste

ordenacao.o: ordenacao.c  ordenacao.h
	gcc -Wall -pedantic -ansi -g -c ordenacao.c -I. -o ordenacao

clean:
	rm ep3_alberto_bcc.o ep3


 ordenacao.c  ordenacao.h  ordenacaoTeste.c  teste
